version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./templates:/etc/nginx/templates
    - /home/ubuntu/certs:/etc/nginx/certs
    ports:
    - "80:80"
    - "443:443"
    environment:
    - NGINX_HOST=cv.kevinsee.com
    - NGINX_PORT=80
    - NGINX_SSL_PORT=443
    container_name: my_cv
